apiVersion: apps/v1
kind: Deployment
metadata:
  name: libro-read-one
spec:
  replicas: 3
  selector:
    matchLabels:
      app: libro-read-one
  template:
    metadata:
      labels:
        app: libro-read-one
    spec:
      containers:
      - name: libro-read-one
        image: rflorezeam/libro-read-one:sha-7fe5f4c
        ports:
        - containerPort: 8083
        env:
        - name: MONGODB_URI
          value: mongodb://root:example@libro-mongodb:27017